Fixed SPEC-TDC timestamp rounding error
SBNSoftware/sbndaq-artdaq-core pull request #110
Opened 2024-08-11 21:12 UTC by VCLanNguyen

### Description

fix unsigned integer truncating decimal, now doing correct rounding and added picosecond timestamp

_If the full description is in a PR from a different repo, simply link that here, and delete the rest._

### Related Repository Branches

List related branches from other repos here (links to PRs even better!), if not linked above.

### Testing details
_(Note: edit as appropriate.)_
- *Where it was tested*: (e.g. SBN-FD, SBN-ND, DAB, etc.) SBN-ND
- *Run number associated with test*: 
- Other information:

2024-08-13 15:02 UTC, eyandel requested changes
The "uint" variable are ints so shouldn't have a decimal.

2024-08-27 22:39 UTC, VCLanNguyen commented
> The "uint" variable are ints so shouldn't have a decimal.

Without the decimal place, the code rounds down instead of rounding correctly. I'll look into Dante's solution and others if it resolves the round issue without using decimal place.

2024-08-28 15:02 UTC, VCLanNguyen commented
> > The "uint" variable are ints so shouldn't have a decimal.
> 
> Without the decimal place, the code rounds down instead of rounding correctly. I'll look into Dante's solution and others if it resolves the round issue without using decimal place.

The decimal forces the code to do the maths in float, then recast into unsigned int. So it is needed for the rounding to be done correctly.

2024-08-28 15:17 UTC, eyandel approved these changes

2024-09-27 18:20 UTC, merged